import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useContext } from 'react'
import { GlobalCtx } from '../context/GlobalCtx'
import connectToSocket from '../lib/connectToSocket'
import AppRouting from '../components/AppRouting'
import { useRouter } from 'next/router'

let socketAPI: UserSocketAPI
export default function Home() {
  const { state, dispatch } = useContext(GlobalCtx)
  const router = useRouter()

  const handleClearStorage = () => {
    dispatch({ type: 'clearStorage' })
    router.reload()
  }

  useEffect(() => {
    const onNewMessage = (msg: string) => {
      dispatch({ type: 'setMsg', payload: msg })
    }
    const socketInit = async () => {
      socketAPI = (await connectToSocket({
        path: '/',
        msgHandler: onNewMessage,
        name: ''
      })) as UserSocketAPI
      dispatch({ type: 'setSocket', payload: socketAPI })
    }
    socketInit().then(() => {
      socketAPI.requestSync()
    })
  }, [dispatch])

  return (
    <AppRouting>
      <div className={styles.container}>
        <Head>
          <title>{state.msg}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="grid gap-4 max-w-md mx-auto">
          <h1 className="text-3xl">Hi {state.name}! </h1>
          <div className={styles.card}>
            <pre>
              <code>&gt; {state.msg}</code>
            </pre>
          </div>
          <div className="flex justify-end">
            <button onClick={handleClearStorage} className="btn btn-link">
              Log Out
            </button>
          </div>
        </main>
      </div>
    </AppRouting>
  )
}
