import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { io, Socket } from 'socket.io-client'
import { useState, useEffect } from 'react'

let socket: Socket<ServerToClientEvents, ClientToServerEvents>
export default function Home() {
  const [message, setmessage] = useState('App name')
  useEffect(() => {
    const socketInit = async () => {
      await fetch('/api/socket')
      socket = io()
      socket.on('connect', () => {
        console.log('Player connected')
      })

      socket.on('updateMessage', (msg) => {
        setmessage(msg)
      })
    }
    socketInit()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>{message}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Work in progress...</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
